### ISSUE TITLE
PacketTooBigException might cause java.sql.SQLException: The active SQL connection has changed due to a connection failure.

### ISSUE THREAD

**Issue by evaelliu** [awslabs/aws-mysql-jdbc#371]
Driver Version: 1.0.0

there are lots of _java.sql.SQLException: The active SQL connection has changed due to a connection failure._  after this _PacketTooBigException_ error happened,  and service running normally after restarted , there might be some non-available connection not released, and they were still reused

origin error:
`Caused by: software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.exceptions.PacketTooBigException: Packet for query is too large (85,887 > 65,535). You can change this value on the server by setting the 'max_allowed_packet' variable.
        at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:107) ~[aws-mysql-jdbc-1.0.0.jar!/:?]
        at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[aws-mysql-jdbc-1.0.0.jar!/:?]
        at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:371) ~[aws-mysql-jdbc-1.0.0.jar!/:?]
        at sun.reflect.GeneratedMethodAccessor607.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.ConnectionProxy$JdbcInterfaceProxy.lambda$invoke$0(ConnectionProxy.java:322) ~[aws-mysql-jdbc-1.0.0.jar!/:?]
        at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.DefaultConnectionPlugin.execute(DefaultConnectionPlugin.java:75) ~[aws-mysql-jdbc-1.0.0.jar!/:?]
        at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.NodeMonitoringConnectionPlugin.execute(NodeMonitoringConnectionPlugin.java:173) ~[aws-mysql-jdbc-1.0.0.jar!/:?]
        at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.failover.FailoverConnectionPlugin.execute(FailoverConnectionPlugin.java:244) ~[aws-mysql-jdbc-1.0.0.jar!/:?]
        at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.ConnectionPluginManager.execute(ConnectionPluginManager.java:133) ~[aws-mysql-jdbc-1.0.0.jar!/:?]
        at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.ConnectionProxy$JdbcInterfaceProxy.invoke(ConnectionProxy.java:319) ~[aws-mysql-jdbc-1.0.0.jar!/:?]
        at com.sun.proxy.$Proxy313.execute(Unknown Source) ~[?:?]
        at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:497) ~[druid-1.2.9.jar!/:1.2.9]
        at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:63) ~[mybatis-3.4.5.jar!/:3.4.5]
        at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79) ~[mybatis-3.4.5.jar!/:3.4.5]
        at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63) ~[mybatis-3.4.5.jar!/:3.4.5]
        at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324) ~[mybatis-3.4.5.jar!/:3.4.5]
        at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156) ~[mybatis-3.4.5.jar!/:3.4.5]
        at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109) ~[mybatis-3.4.5.jar!/:3.4.5]
        at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:108) ~[pagehelper-5.1.11.jar!/:?]
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61) ~[mybatis-3.4.5.jar!/:3.4.5]
        at com.sun.proxy.$Proxy311.query(Unknown Source) ~[?:?]
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148) ~[mybatis-3.4.5.jar!/:3.4.5]
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141) ~[mybatis-3.4.5.jar!/:3.4.5]
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:77) ~[mybatis-3.4.5.jar!/:3.4.5]
        at sun.reflect.GeneratedMethodAccessor754.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433) ~[mybatis-spring-1.3.1.jar!/:1.3.1]
        ... 27 more
`
the following error might caused by using the non-available connection
`Caused by: java.sql.SQLException: The active SQL connection has changed due to a connection failure. Please re-configure session state if required.
        at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.failover.FailoverConnectionPlugin.failover(FailoverConnectionPlugin.java:500) ~[aws-mysql-jdbc-1.0.0.jar!/:?]
        at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.failover.FailoverConnectionPlugin.pickNewConnection(FailoverConnectionPlugin.java:599) ~[aws-mysql-jdbc-1.0.0.jar!/:?]
        at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.failover.FailoverConnectionPlugin.dealWithOriginalException(FailoverConnectionPlugin.java:834) ~[aws-mysql-jdbc-1.0.0.jar!/:?]
        at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.failover.FailoverConnectionPlugin.execute(FailoverConnectionPlugin.java:248) ~[aws-mysql-jdbc-1.0.0.jar!/:?]
        at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.ConnectionPluginManager.execute(ConnectionPluginManager.java:133) ~[aws-mysql-jdbc-1.0.0.jar!/:?]
        at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.ConnectionProxy$JdbcInterfaceProxy.invoke(ConnectionProxy.java:319) ~[aws-mysql-jdbc-1.0.0.jar!/:?]
        at com.sun.proxy.$Proxy313.execute(Unknown Source) ~[?:?]
        at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:497) ~[druid-1.2.9.jar!/:1.2.9]
        at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:46) ~[mybatis-3.4.5.jar!/:3.4.5]
        at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74) ~[mybatis-3.4.5.jar!/:3.4.5]
        at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50) ~[mybatis-3.4.5.jar!/:3.4.5]
        at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117) ~[mybatis-3.4.5.jar!/:3.4.5]
        at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76) ~[mybatis-3.4.5.jar!/:3.4.5]
        at sun.reflect.GeneratedMethodAccessor624.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63) ~[mybatis-3.4.5.jar!/:3.4.5]
        at com.sun.proxy.$Proxy311.update(Unknown Source) ~[?:?]
        at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198) ~[mybatis-3.4.5.jar!/:3.4.5]
        at sun.reflect.GeneratedMethodAccessor780.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433) ~[mybatis-spring-1.3.1.jar!/:1.3.1]
        ... 30 more`

**Comment by aaronchung-bitquill** [comment]
Hi @evaelliu 

Thanks for reaching out and raising this issue. 
We'll be taking a look at this and keep you up to date as we investigate. 

Thank you for your patience.

**Comment by aaronchung-bitquill** [comment]
Hi @little-apppple 

This issue sounds similar to a bug that has since been fixed in version 1.1.0 and newer. Would you mind checking out latest version 1.1.4 to see this resolves the issue? 

In the mean time, would you be able to provide some more information about the following? 

1. What frameworks are you using (like Spring or Hibernate)
2. Are you using any connection pools? (like HikariCP)
3. Are you using an Aurora MySQL DB cluster or any other MySQL server?
4. What your connection string looks like? Does it use IP address, domain name, localhost?
5. When/how often are each of the exceptions happening? 
6. Do you see any relations between your exceptions and DB cluster failover events?

Thank you!

**Comment by little-apppple** [comment]
> 
there's no more errors when we upgraded this version to 1.1.4 , and added the 'maxAllowedPacket'  to jdbcUrl, but I'm still afraid that the connection exception might be triggered by another exception next time.

1.Springboot
2.Druid
3.Aurora MySQL DB cluster 
4.domain name
5. PacketTooBigException is just for the first time,  the SQLException appeared every 2 minutes(not exactly) after the PacketTooBigException happed
6.there were no DB cluster failover events

**Comment by aaronchung-bitquill** [comment]
Hi @little-apppple 

I wanted to clarify that you do not see either exceptions anymore?

Also, I do not think you should be seeing the connection exception anymore, except in DB cluster failover situations. 
For a little more information on that exception, it appears to be a  [Communications Link Failover exception](https://github.com/awslabs/aws-mysql-jdbc#08s02---communication-link). 
It happens when the driver throws a SQLException with code 08S02, the original connection failed while autocommit was set to true, and the driver successfully failed over to another available instance in the cluster. However, any session state configuration of the initial connection is now lost. So if this happens, its recommended that you

1. Reconfigure and reuse the original connection object (so the reconfigured session state will be the same before).
2. Repeat the query that was executed when the connection failed and continue work as desired.

Here is some sample code for an example of how this can be done. [Link ](https://github.com/awslabs/aws-mysql-jdbc#sample-code)

Please let me know if this issue still persists, or if you have another questions/issues. 

Thank you!

**Comment by aaronchung-bitquill** [comment]
Hi @little-apppple 

Have not had a response in about a week, so we will be closing this ticket now. 
If you have still having issues, please feel free to reopen this ticket or create a new one.

Thank you!
