### ISSUE TITLE
JDK17 + aws-jdbc-driver 1.1.4 + Hikari CP 5.0.1 (ArrayIndexOutOfBoundsException: "Range [0, 0 + -16) out of bounds for length 0")

### ISSUE THREAD

**Issue by abedali** [awslabs/aws-mysql-jdbc#375]
### Describe the bug

JDBC Connection is established during the application startup.
But the driver is throwing 'ArrayIndexOutOfBoundsException' which is swallowed. We don't have this exception captured in the application, but our monitoring tool (Overops) is reporting this issue. 

https://app.overops.com/tale.html?event=UzQyMDQyIzE0MDgyIzk-&source=17&gt=mpack

ArrayIndexOutOfBoundsException: Range [0, 0 + -16) out of bounds for length 0
	at jdk.internal.util.Preconditions$1.apply(String, List)
	at jdk.internal.util.Preconditions$1.apply(Object, Object)
	at jdk.internal.util.Preconditions.outOfBounds(BiFunction, String, Number[])
	at jdk.internal.util.Preconditions.outOfBoundsCheckFromIndexSize(BiFunction, int, int, int)
	at jdk.internal.util.Preconditions.checkFromIndexSize(int, int, int, BiFunction)
	at sun.security.util.ArrayUtil.nullAndBoundsCheck(byte[], int, int)
	at com.sun.crypto.provider.GaloisCounterMode$GCMDecrypt.doFinal(byte[], int, int, byte[], int)
	at com.sun.crypto.provider.GaloisCounterMode.engineDoFinal(byte[], int, int)
	at javax.crypto.Cipher.doFinal()
	at sun.security.ssl.SSLCipher$T12GcmReadCipherGenerator$GcmReadCipher.dispose()
	at sun.security.ssl.InputRecord.close()
	at sun.security.ssl.TransportContext.initiateInboundClose()
	at sun.security.ssl.TransportContext.closeInbound()
	at sun.security.ssl.SSLSocketImpl.shutdownInput(boolean)
	at sun.security.ssl.SSLSocketImpl.bruteForceCloseInput(boolean)
	at sun.security.ssl.SSLSocketImpl.duplexCloseOutput()
	at sun.security.ssl.SSLSocketImpl.close()
	at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.protocol.NetworkResources.forceClose()
	at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.protocol.AbstractSocketConnection.forceClose()
	at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.protocol.a.SimplePacketReader.readHeaderLocal()
	at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.protocol.a.SimplePacketReader.readHeader()
	at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.protocol.a.SimplePacketReader.readHeader()
	at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader()
	at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.protocol.a.TimeTrackingPacketReader.readHeader()
	at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.protocol.a.MultiPacketReader.readHeader()
	at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.protocol.a.MultiPacketReader.readHeader()
	at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativePacketPayload)
	at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(int)
	at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.protocol.a.NativeProtocol.sendCommand(Message, boolean, int)
	at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.protocol.a.NativeProtocol.sendCommand(Message, boolean, int)
	at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.NativeSession.ping(boolean, int)
	at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ConnectionImpl.pingInternal(boolean, int)
	at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ConnectionImpl.isValid(int)
	at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.Monitor.checkConnectionStatus(long)
	at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.Monitor.run()
	at java.util.concurrent.Executors$RunnableAdapter.call()
	at java.util.concurrent.FutureTask.run()
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor$Worker)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run()
	at java.lang.Thread.run()

![image](https://user-images.githubusercontent.com/6654386/225654491-82fb0e85-637e-4e01-b902-18ba663ac65e.png)

### Expected Behavior

JDBC Driver isn't supposed to throw ArrayIndexOutOfBoundsException.

### Current Behavior

JDBC Driver is throwing ArrayIndexOutOfBoundsException and it is caught in out monitoring agent.

### Reproduction Steps

General steps of establishing JDBC using Hikari DataSource configuration.

### The AWS JDBC Driver for MySQL version used

1.1.1 RDS mySQL

### JDK version used

Amazon.com Inc OpenJDK 64-Bit Server VM, 17.0.6+10-LTS

### Operating System and version

Linux 4.14.273-207.502.amazon

**Comment by aaronchung-bitquill** [comment]
Hi @abedali 

Thanks for reaching out and raising this issue. 

We'll take a look at this and keep you updated as we investigate. 

Thank you for your patience!

**Comment by aaronchung-bitquill** [comment]
Hi @abedali 

I am currently trying to reproduce this. Can you provide us with any information about the following?

- what plugins are you using?
- how do you have the Hikari Datasource configured?
- any other relevant properties/configurations you can think of

Thank you

**Comment by abedali** [comment]
what plugins are you using?
how do you have the Hikari Datasource configured?
any other relevant properties/configurations you can think of

**Comment by aaronchung-bitquill** [comment]
Hi @abedali 

Apologies for the late reply. 

It looks like the `ArrayIndexOutOfBoundsException` that is thrown, is caught. Subsequent exceptions that are thrown are also caught and ultimately swallowed.

This explains why its visible on OverOps, but not in the application logs.

Other than showing up in OverOps, is this causing any issues? 

---

Also, slightly off topic, but I noticed in your Hikari DS configurations that the `exceptionOverrideClassName` configuration is not set. I'd highly recommend reading the [Connection Pooling part of the documentation ](https://github.com/awslabs/aws-mysql-jdbc#connection-pooling). The gist is that many connection pooling libraries such as Hikari have additional logic for handling SQLExceptions. Unfortunately, this means the exceptions raised by the `aws-mysql-jdbc` driver may not be recognized, and depending on the connection pool, it may prematurely close connections due to the unrecognized SQL exceptions. The recommendation for users is to implement some code that will allow the connection pool to accept the exceptions raised by the driver. To do this for HikariCP, this would be creating an implementation of the `SQLExceptionOverride` interface, and setting the Hikari configuration `exceptionOverrideClassName` to the class name of the implementing class.

Here is an example implementation of the `SQLExceptionOverride` interface

```java
import com.zaxxer.hikari.SQLExceptionOverride;

import java.sql.SQLException;

public class HikariCPSQLException implements SQLExceptionOverride {
    public Override adjudicate(final SQLException sqlException) {
        String sqlState = sqlException.getSQLState();
        if (sqlState.equalsIgnoreCase("08S02") ||
            sqlState.equalsIgnoreCase("08007")) {
            return Override.DO_NOT_EVICT;
        } else {
            return Override.CONTINUE_EVICT;
        }
    }
}
```

Thank you

**Comment by abedali** [comment]
thanks @aaronchung-bitquill for the guidelines and confirming about swallowed exception 'ArrayIndexOutOfBoundsException'.

**Comment by aaronchung-bitquill** [comment]
Hi @abedali 
Wanted to give you a heads up that we will be closing this ticket. However, if you have any more issues or questions, please feel free to either re-open this ticket or create a new one. 
Thank you!
