### ISSUE TITLE
DST timezone bug during spring forward

### ISSUE THREAD

**Issue by slinan** [awslabs/aws-mysql-jdbc#386]
### Describe the bug

During spring forward (turn clocks ahead and lose an hour) I was unable to connect to the DB using the driver. This was the exception thrown: `java.lang.IllegalArgumentException: HOUR_OF_DAY: 2 -> 3.`

The database is in UTC and the JVM is in PT. The error is originated by a driver method that queries the topology for Aurora and decodes a date from `information_schema.replica_host_status`  The cluster returns a UTC datetime, Aurora driver gets PT timezone from the JVM and the exception is thrown.

### Expected Behavior

The driver should be able to translate the timezone or catch the exception

### Current Behavior

This is the stacktrace for the `java.lang.IllegalArgumentException: HOUR_OF_DAY: 2 -> 3.`

```
at java.util.GregorianCalendar.computeTime(GregorianCalendar.java:2829)
at java.util.Calendar.updateTime(Calendar.java:3393)
at java.util.Calendar.getTimeInMillis(Calendar.java:1782)
at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.result.SqlTimestampValueFactory.localCreateFromDatetime(SqlTimestampValueFactory.java:191) at
software.aws.rds.jdbc.mysql.shading.com.mysql.cj.result.SqlTimestampValueFactory.localCreateFromDatetime(SqlTimestampValueFactory.java:51) at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.result.AbstractDateTimeValueFactory.createFromDatetime(AbstractDateTimeValueFactory.java:104)
at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.protocol.a.MysqlTextValueDecoder.decodeDatetime(MysqlTextValueDecoder.java:90)
at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.protocol.result.AbstractResultsetRow.decodeAndCreateReturnValue(AbstractResultsetRow.java:86)
at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.protocol.result.AbstractResultsetRow.getValueFromBytes(AbstractResultsetRow.java:243)
at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.protocol.a.result.ByteArrayRow.getValue(ByteArrayRow.java:91)
at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.result.ResultSetImpl.getTimestamp(ResultSetImpl.java:947)
at
software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.result.ResultSetImpl.getTimestamp(ResultSetImpl.java:985)
at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.failover.AuroraTopologyService.getPropertiesFromTopology(AuroraTopologyService.java:359)
at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.failover.AuroraTopologyService.createHost(AuroraTopologyService.java:324)
at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.failover.AuroraTopologyService.processQueryResults(AuroraTopologyService.java:280)
at
software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.failover.AuroraTopologyService.queryForTopology(AuroraTopologyService.java:232)
at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.failover.AuroraTopologyService.getTopology(AuroraTopologyService.java:200)
at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.failover.FailoverConnectionPlugin.fetchTopology(FailoverConnectionPlugin.java:1016)
at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.failover.FailoverConnectionPlugin.initializeTopology(FailoverConnectionPlugin.java:436)
at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.failover.FailoverConnectionPlugin.initFromConnectionString(FailoverConnectionPlugin.java:969)
at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.failover.FailoverConnectionPlugin.initProxy(FailoverConnectionPlugin.java:1001)
at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.failover.FailoverConnectionPlugin.openInitialConnection(FailoverConnectionPlugin.java:222)
at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.ConnectionPluginManager.openInitialConnection(ConnectionPluginManager.java:151)
```

### Reproduction Steps
Try to query or connect to the DB when:
- The database is in UTC and the JVM is in PT
- It only happens during the spring forward hour

### Possible Solution

Catch the exception and translate the timezone

### The AWS JDBC Driver for MySQL version used

1.1.0

### JDK version used

1.8

### Operating System and version

Amazon Linux 2

**Comment by aaronchung-bitquill** [comment]
Hi @slinan 

Thanks for reaching out to us and raising this issue. 

We will be taking a look at this and keep you up to date with any updates as we investigate. 

Thank you for your patience!

**Comment by slinan** [comment]
Thanks!!

**Comment by aaronchung-bitquill** [comment]
Hi @slinan 
We've just merged in a fix. This bug might be a bit difficult to replicate due to only happening during daylight saving events, but if you like, you can checkout our [snapshot](https://github.com/awslabs/aws-mysql-jdbc#using-a-snapshot-of-the-driver) build and give it a try. 
Please let us know if the issue still persists or if you have any other issues.
Thank you!

**Comment by slinanromero** [comment]
Hey @aaronchung-bitquill ! Thanks a lot for the quick fix! 

Will test in the following weeks!

**Comment by slinan** [comment]
Hey @aaronchung-bitquill ! Thanks for the quick fix!
Will test and let you know in the following weeks

**Comment by slinan** [comment]
Hey @aaronchung-bitquill ! 

I was checking the code and doing some tests but it seems you added a catch for `software.aws.rds.jdbc.mysql.shading.com.mysql.cj.exceptions.WrongArgumentException` but `results.getTimestamp` returns a  `java.lang.IllegalArgumentException` and hence it is not catching the error. Could you help me validate?

**Comment by aaronchung-bitquill** [comment]
Hi @slinan 

My apologies. Taking a look now!

Thank you!

**Comment by slinan** [comment]
Hey @aaronchung-bitquill ! My bad, just saw this code in  `software.aws.rds.jdbc.mysql.shading.com.mysql.cj.result.SqlTimestampValueFactory` `SqlTimestampValueFactory.java:191`
```
            try {
                // this method is HUGEly faster than Java 8's Calendar.Builder()
                c.set(its.getYear(), its.getMonth() - 1, its.getDay(), its.getHours(), its.getMinutes(), its.getSeconds());
                Timestamp ts = new Timestamp(c.getTimeInMillis());
                ts.setNanos(its.getNanos());
                return ts;
            } catch (IllegalArgumentException e) {
                throw ExceptionFactory.createException(WrongArgumentException.class, e.getMessage(), e);
            }
```

Will try to do some manual tests between today and tomorrow and will keep you posted. Thanks a lot!!

**Comment by aaronchung-bitquill** [comment]
Hi @slinan 

Wanted to check in to see if you got a chance to test this out? 

Otherwise, if there are no further updates on this ticket in the next 3 days, we will close this ticket. However, if you require if you find that this issue persists or if you have further issues, you can reopen this issue, or create a new one.

Thank you

**Comment by slinan** [comment]
Hey! Thanks! I validated with unit tests and it is working! 

Also tried to do some manual tests but the issue is really difficult to replicate.

**Comment by aaronchung-bitquill** [comment]
Thank you for confirming, @slinan!

We will now be closing this ticket.
