### ISSUE TITLE
ResultsetRowsStreaming is still active after closing ResultSet and Statement

### ISSUE THREAD

**Issue by eugenePHD** [awslabs/aws-mysql-jdbc#387]
With streaming result sets (created after setFetchSize(Integer.MIN_VALUE)), the documentation states:
"You must read all of the rows in the result set (**or close it**) before you can issue any other queries on the connection, or an exception will be thrown."

This is not the case with AWS jdbc driver. If I do not read all the rows, I cannot issue any more queries even though the result set (and statement) was closed. Even the exception message itself says that you need to call  .close() on any active streaming result set, but the .close() does not have any effect.

`java.sql.SQLException: Streaming result set software.aws.rds.jdbc.mysql.shading.com.mysql.cj.protocol.a.result.ResultsetRowsStreaming@4a3be6a5 is still active. No statements may be issued when any streaming result sets are open and in use on a given connection. Ensure that you have called .close() on any active streaming result sets before attempting more queries.
	at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[aws-mysql-jdbc-1.1.5.jar:?]
	at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[aws-mysql-jdbc-1.1.5.jar:?]
	at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.StatementImpl.executeSimpleNonQuery(StatementImpl.java:1241) ~[aws-mysql-jdbc-1.1.5.jar:?]
	at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.StatementImpl.setupStreamingTimeout(StatementImpl.java:632) ~[aws-mysql-jdbc-1.1.5.jar:?]
	at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:947) ~[aws-mysql-jdbc-1.1.5.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.ConnectionProxy$JdbcInterfaceProxy.lambda$invoke$0(ConnectionProxy.java:348) ~[aws-mysql-jdbc-1.1.5.jar:?]
	at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.DefaultConnectionPlugin.execute(DefaultConnectionPlugin.java:80) ~[aws-mysql-jdbc-1.1.5.jar:?]
	at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.NodeMonitoringConnectionPlugin.execute(NodeMonitoringConnectionPlugin.java:249) ~[aws-mysql-jdbc-1.1.5.jar:?]
	at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.failover.FailoverConnectionPlugin.execute(FailoverConnectionPlugin.java:277) ~[aws-mysql-jdbc-1.1.5.jar:?]
	at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.ConnectionPluginManager.execute(ConnectionPluginManager.java:138) ~[aws-mysql-jdbc-1.1.5.jar:?]
	at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.ConnectionProxy$JdbcInterfaceProxy.invoke(ConnectionProxy.java:345) ~[aws-mysql-jdbc-1.1.5.jar:?]
	at com.sun.proxy.$Proxy20.executeQuery(Unknown Source) ~[?:?]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[HikariCP-3.3.1.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[HikariCP-3.3.1.jar:?]`

The AWS JDBC Driver for MySQL version used

1.1.5

**Comment by aaronchung-bitquill** [comment]
Hi @eugenePHD 

Thank you for reaching out and raising this issue. 

We will be looking at this and keep you up to date as we investigate this. 

Thank you for your patience!

**Comment by crystall-bitquill** [comment]
Hi @eugenePHD ,

We're currently investigating this issue. If possible, could you please provide us with the following information:
- Driver logs (there is documentation on how to enable them [here](https://github.com/awslabs/aws-mysql-jdbc#enable-logging))
- Your Hikari configuration
- A sample of your code

Thank you!

**Comment by eugenePHD** [comment]
The behavior is extremely easy to reproduce. Hickari CP has nothing to do
with it, the direct connection created through DriverManager behaves the
same way.
Steps:

1. Create a connection to Aurora using AWS MySQL jdbc driver
   Connection con = DriverManager.getConnection("jdbc:mysql:aws://" +
hostName + ...
2. Create a PreparedStatement (with a SELECT query that returns some rows)
and set the fetch size to Integer.MIN_VALUE
   PreparedStatement psmt = con.prepareStatement(sql);
3. Execute query with executeQuery() on the statement.
   psmt.setFetchSize(Integer.MIN_VALUE);
4. Store the result set into a ResultSet variable but do not read from it
(or read but not all rows).
   ResultSet rset = psmt.executeQuery();
5. Close result set and prepared statement.
   rset.close();
   psmt.close();
6. Repeat steps 2-3 and observe the exception.

**Comment by crystall-bitquill** [comment]
Thank you for providing reproduction steps!

We've tried reproducing this issue by following your steps, but we have not seen the same behaviour and no exceptions occur.

We used JDK version 1.8, with the AWS JDBC Driver for MySQL version 1.1.5, to connect to an Aurora database using the following code snippet. Is there anything missing or different in this example or environment?

```
    public static void main(String[] args) throws SQLException {

        String query = "SELECT * from table_name";

        try (Connection conn = DriverManager.getConnection("jdbc:mysql:aws://db-identifier.cluster-XYZ.us-east-2.rds.amazonaws.com:3306/database_name")) {
            PreparedStatement pstmt1 = conn.prepareStatement(query);
            pstmt1.setFetchSize(Integer.MIN_VALUE);
            ResultSet rs1 = pstmt1.executeQuery();
            rs1.close();
            pstmt1.close();

            PreparedStatement pstmt2 = conn.prepareStatement(query);
            pstmt2.setFetchSize(Integer.MIN_VALUE);
            // no exceptions occurs here:
            ResultSet rs2 = pstmt2.executeQuery();
            rs2.close();
            pstmt2.close();
        }
    }
```

**Comment by eugenePHD** [comment]
I'm very sorry. I found a mistake in my own code (the result set was being
closed in catch() rather than finally). This is not a bug.

**Comment by eugenePHD** [comment]
Not a bug. Found issue in my code.
