### ISSUE TITLE
Random IndexOutOfBoundsException occurences

### ISSUE THREAD

**Issue by jebeaudet** [awslabs/aws-mysql-jdbc#417]
### Describe the bug

We're getting random `IndexOutOfBoundsException` exceptions. 

### Expected Behavior

The driver code should be safe from those exceptions.

### Current Behavior

Stack trace : 
```
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 1
    at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
    at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
    at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
    at java.util.Objects.checkIndex(Objects.java:372)
    at java.util.ArrayList.get(ArrayList.java:459)
    at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.failover.FailoverConnectionPlugin.updateHostIndex(FailoverConnectionPlugin.java:1292)
    at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.failover.FailoverConnectionPlugin.updateTopologyIfNeeded(FailoverConnectionPlugin.java:737)
    at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.failover.FailoverConnectionPlugin.execute(FailoverConnectionPlugin.java:274)
    at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.plugins.ConnectionPluginManager.execute(ConnectionPluginManager.java:138)
    at software.aws.rds.jdbc.mysql.shading.com.mysql.cj.jdbc.ha.ConnectionProxy$JdbcInterfaceProxy.invoke(ConnectionProxy.java:345)
    at com.sun.proxy.$Proxy168.executeQuery
    at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
    at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
```

### Reproduction Steps

We're using Spring + Hibernate + Hikari FWIW. Unfortunately, I cannot provide a simple way to reproduce. During the bug, no failover or cluster change was happening, it just happened out of nowhere.

### The AWS JDBC Driver for MySQL version used

1.1.7

### JDK version used

11

### Operating System and version

linux

**Comment by crystall-bitquill** [comment]
Hi @jebeaudet,

Thanks for raising this issue.

We'll take a look at this and keep you updated as we investigate.

In the meantime, could you please provide some additional details regarding the following?
- What does the connection URL look like, and what connection parameters are being used?
- What does the Hikari configuration look like?
- Cluster structure: How many database nodes are there?
- Driver logs, which can be enabled as seen [here](https://github.com/awslabs/aws-mysql-jdbc#enable-logging).

Thank you for your patience!

**Comment by jebeaudet** [comment]
> What does the connection URL look like, and what connection parameters are being used?

`jdbc:mysql:aws://CLUSTER_ID.cluster-RANDOM_STRING.us-east-1.rds.amazonaws.com:3306/DATABASE?autoReconnect=true&rewriteBatchedStatements=true&socketTimeout=60000`

> What does the Hikari configuration look like?

```
    hikari:
      maxLifetime: 600000
      maximumPoolSize: 50
      minimumIdle: 10
      idleTimeout: 300000
      connectionTimeout: 5000
      validationTimeout: 2000
```
The rest of the parameters are Spring's defaults.


> Cluster structure: How many database nodes are there?

It's a regional cluster with only 1 primary with version `5.7.mysql_aurora.2.11.1`.

> Driver logs, which can be enabled as seen [here](https://github.com/awslabs/aws-mysql-jdbc#enable-logging).

It's was really a one of.

**Comment by jebeaudet** [comment]
Hi @karenc-bq 

Thanks for the quick fix! It's a bit hard for me to test snapshots but we're eager to bump released versions, I'll circle back here if it ever pops up again when this fix lands the next released version.

Thanks again!

**Comment by karenc-bq** [comment]
Hi @jebeaudet, we [released a new version](https://github.com/awslabs/aws-mysql-jdbc/releases/tag/1.1.8) containing this fix. We will be closing this issue now, please don't hesitate to reach out again if the issue persists. Thank you again for raising this issue.
